### ISSUE TITLE
粽子的代码缺少很多，能提供相关代码学习下吗？谢谢

### ISSUE THREAD

**Issue by skywalkers2012** [qianduanwuzi/H5-game#1]

**Comment by qianduanwuzi** [comment]
可以加wx

**Comment by qianduanwuzi** [comment]
可以加wx：cn2011043607




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"skywalker"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月5日(星期五) 下午4:51
收件人:&nbsp;"qianduanwuzi/H5-game"<H5-game@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qianduanwuzi/H5-game] 粽子的代码缺少很多，能提供相关代码学习下吗？谢谢 (#1)

**Comment by qianduanwuzi** [comment]
现已重新整合架构，可看完整页面实现思路~

**Comment by qianduanwuzi** [comment]
现已重新构建框架，可看页面具体实现思路~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"skywalker"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月5日(星期五) 下午4:51
收件人:&nbsp;"qianduanwuzi/H5-game"<H5-game@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qianduanwuzi/H5-game] 粽子的代码缺少很多，能提供相关代码学习下吗？谢谢 (#1)
