### ISSUE TITLE
有个问题想请教你。

### ISSUE THREAD

**Issue by rick-liruixin** [qianduanwuzi/H5-game#17]
涂抹抽奖那块的逻辑有一处不太明白，为什么for循环要这样写呢？但是这个循环比我的map循环好像计算的又要准确很多。所以想请教一下这个for循环
for (var i = 3, len = data.length; i < len; i += 4) {
        if (data[i] === 0) {
          scrapeNum++;
        }
      }

**Comment by qianduanwuzi** [comment]
ctx.getImageData(x,x,x,x).data返回的是一个数组，存储的是一个当前矩形区域内像素点的集合，以 RGBA 顺序的数据，数据使用  0 至 255（包含）的整数表示由四个像素点元素组成。故需要循环4次，少的话肯定会少取点像素，故失精准了～
